services:
  backend:
    build: ./backend
    ports:
      - "33101:33101"
    restart: unless-stopped

  frontend:
    build: .
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - backend
